### ISSUE TITLE
4.1.0: Generic entity types: CS0246 Namespace or assembly reference not found

### ISSUE THREAD

**Issue by lngr** [JasperFx/marten#1984]
The new Lamar code generation in 4.x appearently does not properly reference all assemblies when using generic entity classes.  This used to work in 3.x and it also works with 4.1.0 if the type arguments are in the same assembly as the generic type.

I have prepared a minimum working example that triggers the bug here: https://github.com/lngr/marten-lamar

Basically you need to:

- have a generic entity `GenericEntity<T>` defined in project A (`ClassLibBase`):
```
public class GenericEntity<T>
{
    public Guid Id { get; set; }
    public T Data { get; set; }
}
```
- have a second "model class" defined in project B (`ClassLibModels`):
```
public class MyData
{
    public string SomeField { get; set; }
}
```
- try to store the entity from a third project C (`WebApp`), which also defines the store:
```
session.Store(new GenericEntity<MyData>
{
    Id = Guid.NewGuid(),
    Data = new MyData
    {
        SomeField = "foo"
    }
});
```

This triggers the following exception due to a lamar compilation error:
```
Unhandled exception. System.InvalidOperationException: Compilation failures!

CS0246: The type or namespace name ‘ClassLibModels’ could not be found (are you missing a using directive or an assembly reference?)
[... repeated a number of times]

Code:

using ClassLibBase;
using Marten.Internal;
using Marten.Internal.Storage;
using Marten.Schema;
using Marten.Schema.Arguments;
using Npgsql;
using System;
using System.Collections.Generic;
using Weasel.Core;
using Weasel.Postgresql;

namespace Marten.Generated
{
    // START: UpsertGenericEntity_1Operation
    public class UpsertGenericEntity_1Operation : Marten.Internal.Operations.StorageOperation<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly ClassLibBase.GenericEntity<ClassLibModels.MyData> _document;
        private readonly System.Guid _id;
        private readonly System.Collections.Generic.Dictionary<System.Guid, System.Guid> _versions;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public UpsertGenericEntity_1Operation(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, System.Guid id, System.Collections.Generic.Dictionary<System.Guid, System.Guid> versions, Marten.Schema.DocumentMapping mapping) : base(document, id, versions, ma
pping)
        {
            _document = document;
            _id = id;
            _versions = versions;
            _mapping = mapping;
        }



        public override string CommandText()
        {
            return "select public.mt_upsert_genericentitymydata(?, ?, ?, ?)";
        }


        public override NpgsqlTypes.NpgsqlDbType DbType()
        {
            return NpgsqlTypes.NpgsqlDbType.Uuid;
        }


        public override void ConfigureParameters(Npgsql.NpgsqlParameter[] parameters, ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session)
        {
            parameters[0].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Jsonb;
            parameters[0].Value = session.Serializer.ToJson(_document);
            // .Net Class Type
            parameters[1].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
            parameters[1].Value = _document.GetType().FullName;
            parameters[2].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Uuid;
            parameters[2].Value = document.Id;
            setVersionParameter(parameters[3]);
        }


        public override void Postprocess(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions)
        {
            storeVersion();
        }


        public override System.Threading.Tasks.Task PostprocessAsync(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions, System.Threading.CancellationToken token)
        {
            storeVersion();
            // Nothing
            return System.Threading.Tasks.Task.CompletedTask;
        }


        public override Marten.Internal.Operations.OperationRole Role()
        {
            return Marten.Internal.Operations.OperationRole.Upsert;
        }

    }

    // END: UpsertGenericEntity_1Operation


    // START: InsertGenericEntity_1Operation
    public class InsertGenericEntity_1Operation : Marten.Internal.Operations.StorageOperation<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly ClassLibBase.GenericEntity<ClassLibModels.MyData> _document;
        private readonly System.Guid _id;
        private readonly System.Collections.Generic.Dictionary<System.Guid, System.Guid> _versions;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public InsertGenericEntity_1Operation(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, System.Guid id, System.Collections.Generic.Dictionary<System.Guid, System.Guid> versions, Marten.Schema.DocumentMapping mapping) : base(document, id, versions, ma
pping)
        {
            _document = document;
            _id = id;
            _versions = versions;
            _mapping = mapping;
        }



        public override string CommandText()
        {
            return "select public.mt_insert_genericentitymydata(?, ?, ?, ?)";
        }


        public override NpgsqlTypes.NpgsqlDbType DbType()
        {
            return NpgsqlTypes.NpgsqlDbType.Uuid;
        }


        public override void ConfigureParameters(Npgsql.NpgsqlParameter[] parameters, ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session)
        {
            parameters[0].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Jsonb;
            parameters[0].Value = session.Serializer.ToJson(_document);
            // .Net Class Type
            parameters[1].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
            parameters[1].Value = _document.GetType().FullName;
            parameters[2].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Uuid;
            parameters[2].Value = document.Id;
            setVersionParameter(parameters[3]);
        }


        public override void Postprocess(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions)
        {
            storeVersion();
        }


        public override System.Threading.Tasks.Task PostprocessAsync(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions, System.Threading.CancellationToken token)
        {
            storeVersion();
            // Nothing
            return System.Threading.Tasks.Task.CompletedTask;
        }


        public override Marten.Internal.Operations.OperationRole Role()
        {
            return Marten.Internal.Operations.OperationRole.Insert;
        }

    }

    // END: InsertGenericEntity_1Operation


    // START: UpdateGenericEntity_1Operation
    public class UpdateGenericEntity_1Operation : Marten.Internal.Operations.StorageOperation<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly ClassLibBase.GenericEntity<ClassLibModels.MyData> _document;
        private readonly System.Guid _id;
        private readonly System.Collections.Generic.Dictionary<System.Guid, System.Guid> _versions;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public UpdateGenericEntity_1Operation(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, System.Guid id, System.Collections.Generic.Dictionary<System.Guid, System.Guid> versions, Marten.Schema.DocumentMapping mapping) : base(document, id, versions, ma
pping)
        {
            _document = document;
            _id = id;
            _versions = versions;
            _mapping = mapping;
        }



        public override string CommandText()
        {
            return "select public.mt_update_genericentitymydata(?, ?, ?, ?)";
        }


        public override NpgsqlTypes.NpgsqlDbType DbType()
        {
            return NpgsqlTypes.NpgsqlDbType.Uuid;
        }


        public override void ConfigureParameters(Npgsql.NpgsqlParameter[] parameters, ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session)
        {
            parameters[0].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Jsonb;
            parameters[0].Value = session.Serializer.ToJson(_document);
            // .Net Class Type
            parameters[1].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Varchar;
            parameters[1].Value = _document.GetType().FullName;
            parameters[2].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Uuid;
            parameters[2].Value = document.Id;
            setVersionParameter(parameters[3]);
        }


        public override void Postprocess(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions)
        {
            storeVersion();
            postprocessUpdate(reader, exceptions);
        }


        public override async System.Threading.Tasks.Task PostprocessAsync(System.Data.Common.DbDataReader reader, System.Collections.Generic.IList<System.Exception> exceptions, System.Threading.CancellationToken token)
        {
            storeVersion();
            await postprocessUpdateAsync(reader, exceptions, token);
        }


        public override Marten.Internal.Operations.OperationRole Role()
        {
            return Marten.Internal.Operations.OperationRole.Update;
        }

    }

    // END: UpdateGenericEntity_1Operation


    // START: QueryOnlyGenericEntity_1Selector
    public class QueryOnlyGenericEntity_1Selector : Marten.Internal.CodeGeneration.DocumentSelectorWithOnlySerializer, Marten.Linq.Selectors.ISelector<ClassLibBase.GenericEntity<ClassLibModels.MyData>>
    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public QueryOnlyGenericEntity_1Selector(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public ClassLibBase.GenericEntity<ClassLibModels.MyData> Resolve(System.Data.Common.DbDataReader reader)
        {

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 0);
            return document;
        }


        public System.Threading.Tasks.Task<ClassLibBase.GenericEntity<ClassLibModels.MyData>> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 0);
            return System.Threading.Tasks.Task.FromResult(document);
        }

    }

    // END: QueryOnlyGenericEntity_1Selector


    // START: LightweightGenericEntity_1Selector
    public class LightweightGenericEntity_1Selector : Marten.Internal.CodeGeneration.DocumentSelectorWithVersions<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>, Marten.Linq.Selectors.ISelector<ClassLibBase.GenericEntity<ClassLibModels.MyData>>
    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public LightweightGenericEntity_1Selector(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public ClassLibBase.GenericEntity<ClassLibModels.MyData> Resolve(System.Data.Common.DbDataReader reader)
        {
            var id = reader.GetFieldValue<System.Guid>(0);

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            return document;
        }


        public async System.Threading.Tasks.Task<ClassLibBase.GenericEntity<ClassLibModels.MyData>> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {
            var id = await reader.GetFieldValueAsync<System.Guid>(0, token);

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            return document;
        }

    }

    // END: LightweightGenericEntity_1Selector


    // START: IdentityMapGenericEntity_1Selector
    public class IdentityMapGenericEntity_1Selector : Marten.Internal.CodeGeneration.DocumentSelectorWithIdentityMap<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>, Marten.Linq.Selectors.ISelector<ClassLibBase.GenericEntity<ClassLibModels.MyData>>
    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public IdentityMapGenericEntity_1Selector(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public ClassLibBase.GenericEntity<ClassLibModels.MyData> Resolve(System.Data.Common.DbDataReader reader)
        {
            var id = reader.GetFieldValue<System.Guid>(0);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            return document;
        }


        public async System.Threading.Tasks.Task<ClassLibBase.GenericEntity<ClassLibModels.MyData>> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {
            var id = await reader.GetFieldValueAsync<System.Guid>(0, token);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            return document;
        }

    }

    // END: IdentityMapGenericEntity_1Selector


    // START: DirtyTrackingGenericEntity_1Selector
    public class DirtyTrackingGenericEntity_1Selector : Marten.Internal.CodeGeneration.DocumentSelectorWithDirtyChecking<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>, Marten.Linq.Selectors.ISelector<ClassLibBase.GenericEntity<ClassLibModels.MyData>>

    {
        private readonly Marten.Internal.IMartenSession _session;
        private readonly Marten.Schema.DocumentMapping _mapping;

        public DirtyTrackingGenericEntity_1Selector(Marten.Internal.IMartenSession session, Marten.Schema.DocumentMapping mapping) : base(session, mapping)
        {
            _session = session;
            _mapping = mapping;
        }



        public ClassLibBase.GenericEntity<ClassLibModels.MyData> Resolve(System.Data.Common.DbDataReader reader)
        {
            var id = reader.GetFieldValue<System.Guid>(0);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            StoreTracker(_session, document);
            return document;
        }


        public async System.Threading.Tasks.Task<ClassLibBase.GenericEntity<ClassLibModels.MyData>> ResolveAsync(System.Data.Common.DbDataReader reader, System.Threading.CancellationToken token)
        {
            var id = await reader.GetFieldValueAsync<System.Guid>(0, token);
            if (_identityMap.TryGetValue(id, out var existing)) return existing;

            ClassLibBase.GenericEntity<ClassLibModels.MyData> document;
            document = _serializer.FromJson<ClassLibBase.GenericEntity<ClassLibModels.MyData>>(reader, 1);
            _session.MarkAsDocumentLoaded(id, document);
            _identityMap[id] = document;
            StoreTracker(_session, document);
            return document;
        }

    }

    // END: DirtyTrackingGenericEntity_1Selector


    // START: QueryOnlyGenericEntity_1DocumentStorage
    public class QueryOnlyGenericEntity_1DocumentStorage : Marten.Internal.Storage.QueryOnlyDocumentStorage<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public QueryOnlyGenericEntity_1DocumentStorage(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Storage.ITenant tenant)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpdateGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.InsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.QueryOnlyGenericEntity_1Selector(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids);
        }

    }

    // END: QueryOnlyGenericEntity_1DocumentStorage


    // START: LightweightGenericEntity_1DocumentStorage
    public class LightweightGenericEntity_1DocumentStorage : Marten.Internal.Storage.LightweightDocumentStorage<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public LightweightGenericEntity_1DocumentStorage(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Storage.ITenant tenant)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpdateGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.InsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.LightweightGenericEntity_1Selector(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids);
        }

    }

    // END: LightweightGenericEntity_1DocumentStorage


    // START: IdentityMapGenericEntity_1DocumentStorage
    public class IdentityMapGenericEntity_1DocumentStorage : Marten.Internal.Storage.IdentityMapDocumentStorage<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public IdentityMapGenericEntity_1DocumentStorage(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Storage.ITenant tenant)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpdateGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.InsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.IdentityMapGenericEntity_1Selector(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids);
        }

    }

    // END: IdentityMapGenericEntity_1DocumentStorage


    // START: DirtyTrackingGenericEntity_1DocumentStorage
    public class DirtyTrackingGenericEntity_1DocumentStorage : Marten.Internal.Storage.DirtyCheckedDocumentStorage<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly Marten.Schema.DocumentMapping _document;

        public DirtyTrackingGenericEntity_1DocumentStorage(Marten.Schema.DocumentMapping document) : base(document)
        {
            _document = document;
        }



        public override System.Guid AssignIdentity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Storage.ITenant tenant)
        {
            if (document.Id == Guid.Empty) _setter(document, Marten.Schema.Identity.CombGuidIdGeneration.NewGuid());
            return document.Id;
        }


        public override Marten.Internal.Operations.IStorageOperation Update(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpdateGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Insert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.InsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Upsert(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {

            return new Marten.Generated.UpsertGenericEntity_1Operation
            (
                document, Identity(document),
                session.Versions.ForType<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>(),
                _document

            );
        }


        public override Marten.Internal.Operations.IStorageOperation Overwrite(ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Internal.IMartenSession session, Marten.Storage.ITenant tenant)
        {
            throw new System.NotSupportedException();
        }


        public override System.Guid Identity(ClassLibBase.GenericEntity<ClassLibModels.MyData> document)
        {
            return document.Id;
        }


        public override Marten.Linq.Selectors.ISelector BuildSelector(Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.DirtyTrackingGenericEntity_1Selector(session, _document);
        }


        public override Npgsql.NpgsqlCommand BuildLoadCommand(System.Guid id, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loaderSql).With("id", id);
        }


        public override Npgsql.NpgsqlCommand BuildLoadManyCommand(System.Guid[] ids, Marten.Storage.ITenant tenant)
        {
            return new NpgsqlCommand(_loadArraySql).With("ids", ids);
        }

    }

    // END: DirtyTrackingGenericEntity_1DocumentStorage


    // START: GenericEntity_1BulkLoader
    public class GenericEntity_1BulkLoader : Marten.Internal.CodeGeneration.BulkLoader<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid>
    {
        private readonly Marten.Internal.Storage.IDocumentStorage<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid> _storage;

        public GenericEntity_1BulkLoader(Marten.Internal.Storage.IDocumentStorage<ClassLibBase.GenericEntity<ClassLibModels.MyData>, System.Guid> storage) : base(storage)
        {
            _storage = storage;
        }



        public override void LoadRow(Npgsql.NpgsqlBinaryImporter writer, ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Storage.ITenant tenant, Marten.ISerializer serializer)
        {
            writer.Write(document.GetType().FullName, NpgsqlTypes.NpgsqlDbType.Varchar);
            writer.Write(document.Id, NpgsqlTypes.NpgsqlDbType.Uuid);
            writer.Write(Marten.Schema.Identity.CombGuidIdGeneration.NewGuid(), NpgsqlTypes.NpgsqlDbType.Uuid);
            writer.Write(serializer.ToJson(document), NpgsqlTypes.NpgsqlDbType.Jsonb);
        }


        public override async System.Threading.Tasks.Task LoadRowAsync(Npgsql.NpgsqlBinaryImporter writer, ClassLibBase.GenericEntity<ClassLibModels.MyData> document, Marten.Storage.ITenant tenant, Marten.ISerializer serializer, System.Threading.CancellationToken canc
ellation)
        {
            await writer.WriteAsync(document.GetType().FullName, NpgsqlTypes.NpgsqlDbType.Varchar, cancellation);
            await writer.WriteAsync(document.Id, NpgsqlTypes.NpgsqlDbType.Uuid, cancellation);
            await writer.WriteAsync(Marten.Schema.Identity.CombGuidIdGeneration.NewGuid(), NpgsqlTypes.NpgsqlDbType.Uuid, cancellation);
            await writer.WriteAsync(serializer.ToJson(document), NpgsqlTypes.NpgsqlDbType.Jsonb, cancellation);
        }


        public override string MainLoaderSql()
        {
            return "COPY public.mt_doc_genericentitymydata(\"mt_dotnet_type\", \"id\", \"mt_version\", \"data\") FROM STDIN BINARY";
        }


        public override string TempLoaderSql()
        {
            return "COPY mt_doc_genericentitymydata_temp(\"mt_dotnet_type\", \"id\", \"mt_version\", \"data\") FROM STDIN BINARY";
        }


        public override string CreateTempTableForCopying()
        {
            return "create temporary table mt_doc_genericentitymydata_temp as select * from public.mt_doc_genericentitymydata limit 0";
        }


        public override string CopyNewDocumentsFromTempTable()
        {
            return "insert into public.mt_doc_genericentitymydata (\"id\", \"data\", \"mt_version\", \"mt_dotnet_type\", mt_last_modified) (select mt_doc_genericentitymydata_temp.\"id\", mt_doc_genericentitymydata_temp.\"data\", mt_doc_genericentitymydata_temp.\"mt_ve
rsion\", mt_doc_genericentitymydata_temp.\"mt_dotnet_type\", transaction_timestamp() from mt_doc_genericentitymydata_temp left join public.mt_doc_genericentitymydata on mt_doc_genericentitymydata_temp.id = public.mt_doc_genericentitymydata.id where public.mt_doc_gener
icentitymydata.id is null)";
        }


        public override string OverwriteDuplicatesFromTempTable()
        {
            return "update public.mt_doc_genericentitymydata target SET data = source.data, mt_version = source.mt_version, mt_dotnet_type = source.mt_dotnet_type, mt_last_modified = transaction_timestamp() FROM mt_doc_genericentitymydata_temp source WHERE source.id =
 target.id";
        }

    }

    // END: GenericEntity_1BulkLoader


}


   at LamarCompiler.AssemblyGenerator.Generate(String code)
   at LamarCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at Marten.Internal.CodeGeneration.DocumentPersistenceBuilder.Generate[T]()
   at Marten.Internal.ProviderGraph.StorageFor[T]()
   at Marten.Internal.StorageCheckingProviderGraph.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
   at Marten.Internal.Sessions.DocumentSessionBase.store[T](IEnumerable`1 entities)
   at Marten.Internal.Sessions.DocumentSessionBase.Store[T](T[] entities)
   at WebApp.Program.Main(String[] args) in D:\dev\mestus\marten-lamar-bug\WebApp\Program.cs:line 29
   at WebApp.Program.<Main>(String[] args)

Process finished with exit code -532,462,766.
```

**Comment by lngr** [comment]
This is possibly a duplicate of #1851 or a related bug.

**Comment by lngr** [comment]
I've added a pull request with a test case and a fix #1985
